### PR TITLE
update tokenizer

### PR DESCRIPTION
**Pull request by joacasallas**

### CODE REVIEW

**Comment by edisson11osorio** [comment]
changes

**Review by edisson11osorio — COMMENTED** [review]
cambios

**Review by edisson11osorio — APPROVED** [review]

**Review by edisson11osorio — APPROVED** [review]

**Review by edisson11osorio — COMMENTED** [review]
changes

**Review by edisson11osorio — APPROVED** [review]

**Comment by joacasallas** [comment]
closed

**Pull request closed without merging**
